Style/Documentation:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'

require:
  - rubocop-rspec
