Style/Documentation:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/LetSetup:
  Exclude:
    - 'spec/controllers/shared/*'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/features/*'

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'

require:
  - rubocop-rspec
