default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV['DATABASE_POOL'] || 5 %>

development:
  <<: *default
  database: banking_application_development
  username: <%= Rails.application.secrets.db_username %>
  password: <%= Rails.application.secrets.dp_password %>
  host: localhost
  port: 5432

test: &test
  <<: *default
  database: banking_application_test

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
